services:
  db:
    image: postgres:16
    container_name: patients-careexpand-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" 
    volumes:
      - patients_pgdata:/var/lib/postgresql/data

volumes:
  patients_pgdata: